version: 2
models:
  - name: products
    description: List of saleable products, one row per product.
    columns:
      - name: sku
        description: The unique key of the product mart.
        data_type: VARCHAR(250)
        data_tests:
          - not_null
          - unique
      - name: name
        description: Product full name.
        data_type: VARCHAR(250)
      - name: type
        description: Type of saleable product.
        data_type: VARCHAR(250)
        data_tests:
          - accepted_values:
              values: ["jaffle", "beverage"]
      - name: price
        description: The Retail Sales Price of the Product.
        data_type: DOUBLE
      - name: description
        description: The product description.
        data_type: VARCHAR(250)

semantic_models:
  #The name of the semantic model.
  - name: products
    description: |
      Product dimension table. The grain of the table is one row per product.
    #The name of the dbt model and schema
    model: ref('products')
    #Entities. These usually corespond to keys in the table.
    entities:
      - name: product
        type: primary
        expr: product_id
    #Dimensions. Either categorical or time. These add additonal context to metrics. The typical querying pattern is Metric by Dimension.
    dimensions:
      - name: product_name
        type: categorical
      - name: product_type
        type: categorical
      - name: product_description
        type: categorical
      - name: is_food_item
        type: categorical
      - name: is_drink_item
        type: categorical
      - name: product_price
        type: categorical
